# Application And Database Configurations
spring:
  application:
    name: POLICY-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3307/policyDetailsDb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081


# Eureka Configurations
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


